language: ruby
rvm:
  - 2.0.0
  
before_script:
  - psql -c "CREATE USER sustainabilitychecker WITH PASSWORD 'coucou';" -U postgres
  - psql -c "CREATE ROLE sustainabilitychecker WITH SUPERUSER;" -U postgres


