class AdminController < ApplicationController
  layout 'static_pages'
  http_basic_authenticate_with :name => "iaste", :password => (ENV['ADMIN_PWD'] || 'dev')
  
  def admin     
    array = [
      ['checker', 'chkr_dem_low_i',  '/assets/d_dem_low.png'],
      ['checker', 'chkr_dem_med_i',  '/assets/d_dem_med.png'],
      ['checker', 'chkr_dem_high_i', '/assets/d_dem_high.png'],
      ['checker', 'chkr_dem_low_t',  'Less developped countries'],
      ['checker', 'chkr_dem_med_t',  'Emerging economy'],
      ['checker', 'chkr_dem_high_t', 'Post-industrial, rich'],
      ['checker', 'chkr_dem_low_c',  '<small>(e.g. Cambodgia)</small>'],
      ['checker', 'chkr_dem_med_c',  '<small>(e.g. China)</small>'],
      ['checker', 'chkr_dem_high_c', '<small>(e.g. Europe)</small>'],
      ['checker', 'chkr_die_low_i',  '/assets/placeholder.png'],
      ['checker', 'chkr_die_med_i',  '/assets/placeholder.png'],
      ['checker', 'chkr_die_high_i', '/assets/placeholder.png'],
      ['checker', 'chkr_die_low_t',  'Low'],
      ['checker', 'chkr_die_med_t',  'Average'],
      ['checker', 'chkr_die_high_t', 'High'],
      ['checker', 'chkr_die_low_c',  '<small>(eg. Parts of India)</small>'],
      ['checker', 'chkr_die_med_c',  '<small>(eg. Europe)</small>'],
      ['checker', 'chkr_die_high_c', '<small>(eg. USA)</small>'],
      ['checker', 'chkr_den_low_i',  '/assets/placeholder.png'],
      ['checker', 'chkr_den_med_i',  '/assets/placeholder.png'],
      ['checker', 'chkr_den_high_i', '/assets/placeholder.png'],
      ['checker', 'chkr_den_low_t',  'Low'],
      ['checker', 'chkr_den_med_t',  'Average'],
      ['checker', 'chkr_den_high_t', 'High'],
      ['checker', 'chkr_den_low_c',  '<small>(eg. Canada, Russia)</small>'],
      ['checker', 'chkr_den_med_c',  '<small>(eg. USA)</small>'],
      ['checker', 'chkr_den_high_c', '<small>(eg. India, Japan, South Korea)</small>'],
      ['checker', 'chkr_lan_low_i',  '/assets/placeholder.png'],
      ['checker', 'chkr_lan_med_i',  '/assets/placeholder.png'],
      ['checker', 'chkr_lan_high_i', '/assets/placeholder.png'],
      ['checker', 'chkr_lan_low_t',  'Low'],
      ['checker', 'chkr_lan_med_t',  'Average'],
      ['checker', 'chkr_lan_high_t', 'High'],
      ['checker', 'chkr_lan_low_c',  '<small>(eg. Bangladesh)</small>'],
      ['checker', 'chkr_lan_med_c',  '<small>(eg. France, Spain)</small>'],
      ['checker', 'chkr_lan_high_c', '<small>(eg. Canada, Australia)</small>'],
      ['checker', 'chkr_ind_low_i',  '/assets/placeholder.png'],
      ['checker', 'chkr_ind_med_i',  '/assets/placeholder.png'],
      ['checker', 'chkr_ind_high_i', '/assets/placeholder.png'],
      ['checker', 'chkr_ind_low_t',  'Low'],
      ['checker', 'chkr_ind_med_t',  'Average'],
      ['checker', 'chkr_ind_high_t', 'High'],
      ['checker', 'chkr_ind_low_c',  '<small>(eg. Central Africa, China)</small>'],
      ['checker', 'chkr_ind_med_c',  '<small>(eg. Russia, Argentina, Mexico)</small>'],
      ['checker', 'chkr_ind_high_c', '<small>(eg. USA, Australia, France)</small>'],
      ['checker', 'chkr_agr_low_i',  '/assets/placeholder.png'],
      ['checker', 'chkr_agr_med_i',  '/assets/placeholder.png'],
      ['checker', 'chkr_agr_high_i', '/assets/placeholder.png'],
      ['checker', 'chkr_agr_low_t',  'Traditional, Labor-intensive'],
      ['checker', 'chkr_agr_med_t',  'Mixed'],
      ['checker', 'chkr_agr_high_t', 'Industrialized, Mechanized'],
      ['checker', 'chkr_agr_low_c',  '<small>(eg. Central Africa, India)</small>'],
      ['checker', 'chkr_agr_med_c',  '<small>(eg. Brazil, Mexico)</small>'],
      ['checker', 'chkr_agr_high_c', '<small>(eg. USA, Europe, Australia)</small>'],
      ['checker', 'chkr_hou_urb', 'Urban'],
      ['checker', 'chkr_hou_rur', 'Rural'],
      ['checker', 'chkr_hou_sub', 'Rich, Suburbs'],
      ['checker', 'chkr_hou_apa', 'Middle-class, Appartments'],
      ['checker', 'chkr_hou_slu', 'Poor, Slums'],
      ['checker', 'chkr_ser_edu', 'Education &amp; Healthcare'],
      ['checker', 'chkr_ser_med', 'Media, Entertainment, Tourism'],
      ['checker', 'chkr_ser_pub', 'Public Institutions, Government, Military'],
      ['checker', 'chkr_ser_tra', 'Transportation, Retailing'],
      ['checker', 'chkr_ene_ele', 'Electricity'],
      ['checker', 'chkr_ene_nuc', 'Nuclear'],
      ['checker', 'chkr_ene_hyd', 'Hydropower'],
      ['checker', 'chkr_ene_win', 'Wind Power'],
      ['checker', 'chkr_ene_pho', 'Photovoltaics'],
      ['checker', 'chkr_ene_csp', 'Concentrated Solar Power'],
      ['checker', 'chkr_ene_fue', 'Fuels'],
      ['checker', 'chkr_ene_bio', 'Biofuels'],
      ['checker', 'chkr_ene_hyg', 'Hydrogen'],
      ['checker', 'chkr_ene_ncf', 'Non-conventional fossile resources'],
      ['checker', 'chkr_res_title', 'Failed!'],
      ['checker', 'chkr_res_local', 'Local Supply'],
      ['checker', 'chkr_res_imported', 'Imported'],
      ['checker', 'chkr_res_food', 'Food'],
      ['checker', 'chkr_res_energy', 'Energy'],
      ['checker', 'chkr_res_quote', '"A society that relies on imports to function is not sustainable... You failed the check because of..."'],
      ['checker', 'chkr_res_again', 'Try Again'],
      ['checker', 'chkr_res_next', 'Next Level'],
    ]
    for item in array
      c = Content.new(page: item[0], slug: item[1], content: item[2])
      c.save
    end
  end
end

